version: '3.8'

services:
  backend:
    build: .
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules  # To prevent overwriting node_modules inside the container
    working_dir: /app/backend  
    ports:
      - "3000:3000"  # Port mapping for your backend
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # To persist the database data

volumes:
  pgdata:
